### ISSUE TITLE
Fails to compile on Ubuntu 12.04 64bit

### ISSUE THREAD

**Issue by motorsep** [RobertBeckebans/RBDOOM-3-BFG#2]
Linking CXX executable RBDoom3
/home/motorsep/games/RBDOOM-3-BFG/neo/sys/posix/posix_main.cpp:275: error: undefined reference to 'clock_gettime'
/home/motorsep/games/RBDOOM-3-BFG/neo/sys/posix/posix_main.cpp:589: error: undefined reference to 'dlsym'
/home/motorsep/games/RBDOOM-3-BFG/neo/sys/posix/posix_main.cpp:590: error: undefined reference to 'dlerror'
/home/motorsep/games/RBDOOM-3-BFG/neo/sys/posix/posix_main.cpp:569: error: undefined reference to 'dlopen'
/home/motorsep/games/RBDOOM-3-BFG/neo/sys/posix/posix_main.cpp:572: error: undefined reference to 'dlerror'
/home/motorsep/games/RBDOOM-3-BFG/neo/sys/posix/posix_main.cpp:606: error: undefined reference to 'dlclose'
/home/motorsep/games/RBDOOM-3-BFG/neo/sys/linux/linux_main.cpp:216: error: undefined reference to 'clock_gettime'
/home/motorsep/games/RBDOOM-3-BFG/neo/sys/linux/linux_main.cpp:216: error: undefined reference to 'clock_gettime'
/home/motorsep/games/RBDOOM-3-BFG/neo/sys/linux/linux_main.cpp:216: error: undefined reference to 'clock_gettime'
collect2: ld returned 1 exit status
make[2]: **\* [RBDoom3] Error 1
make[1]: **\* [CMakeFiles/RBDoom3.dir/all] Error 2
make: **\* [all] Error 2
