### ISSUE TITLE
Compile error: identifier "VK_API_VERSION_MAJOR"/"VK_API_VERSION_MINOR"/"VK_API_VERSION_PATCH" is undefined

### ISSUE THREAD

**Issue by r-a-sattarov** [RobertBeckebans/RBDOOM-3-BFG#656]
OS: Elbrus 6 (Linux 5.4)
Compiler: mcst-lcc 1.25.22 (gcc 7.3.0 compatible)
Vulkan: 1.2.131
Cmake options: `-DCMAKE_BUILD_TYPE=Release -DSDL2=ON -DONATIVE=ON -DUSE_VULKAN=ON -DSPIRV_SHADERC=OFF -DFFMPEG=OFF -DBINKDEC=ON`
RBDOOM-3-BFG: ee014e80d0a6ccb5d4647a3d9cb48b0e27074b3b

I get compilation errors.
```
lcc: "/home/sattarov/RBDOOM-3-BFG/neo/renderer/Vulkan/RenderBackend_VK.cpp", line 746: error #20:
          identifier "VK_API_VERSION_MAJOR" is undefined
  			version_string.Append( va( "Vulkan API %i.%i.%i", VK_API_VERSION_MAJOR( gpu.props.apiVersion ), VK_API_VERSION_MINOR( gpu.props.apiVersion ), VK_API_VERSION_PATCH( gpu.props.apiVersion ) ) );
  			                                                  ^
lcc: "/home/sattarov/RBDOOM-3-BFG/neo/renderer/Vulkan/RenderBackend_VK.cpp", line 746: error #20:
          identifier "VK_API_VERSION_MINOR" is undefined
  			version_string.Append( va( "Vulkan API %i.%i.%i", VK_API_VERSION_MAJOR( gpu.props.apiVersion ), VK_API_VERSION_MINOR( gpu.props.apiVersion ), VK_API_VERSION_PATCH( gpu.props.apiVersion ) ) );
  			                                                                                                ^
lcc: "/home/sattarov/RBDOOM-3-BFG/neo/renderer/Vulkan/RenderBackend_VK.cpp", line 746: error #20:
          identifier "VK_API_VERSION_PATCH" is undefined
  			version_string.Append( va( "Vulkan API %i.%i.%i", VK_API_VERSION_MAJOR( gpu.props.apiVersion ), VK_API_VERSION_MINOR( gpu.props.apiVersion ), VK_API_VERSION_PATCH( gpu.props.apiVersion ) ) );
  			                                                                                                                                              ^       
3 errors detected in the compilation of "/home/sattarov/RBDOOM-3-BFG/neo/renderer/Vulkan/RenderBackend_VK.cpp"
```

**Comment by SRSaunders** [comment]
`VK_API_VERSION_MAJOR()`, `VK_API_VERSION_MINOR()`, and `VK_API_VERSION_PATCH()` are macros defined within `vulkan_core.h` which is included by `vulkan.h`. The Vulkan spec indicates they are provided since VK_VERSION_1_0.

Is your build environment properly picking up `vulkan.h`?  Note that `RenderBackend_VK.cpp` should be picking this up via `precompiled.h` (which includes `qvk.h` that in turn includes `vulkan.h`).

Can you look inside `vulkan_core.h` to make sure these macros are defined within your setup?

**Comment by r-a-sattarov** [comment]
Yep, Vulkan 1.2.131 uses VK_VERSION_MAJOR(), VK_VERSION_MINOR(), and VK_VERSION_PATCH() macros. My Vulkan libs needs to be updated. Thanks!

P.S. Maybe we can check the version of the Vulkan libraries through cmake (to prevent this compile error)?

**Comment by SRSaunders** [comment]
I think this may be the easiest way to solve it:

```
#if VK_HEADER_VERSION >= 176
	version_string.Append( va( "Vulkan API %i.%i.%i", VK_API_VERSION_MAJOR( gpu.props.apiVersion ), VK_API_VERSION_MINOR( gpu.props.apiVersion ), VK_API_VERSION_PATCH( gpu.props.apiVersion ) ) );
#else
	// SRS - Allow deprecated version macros on older Vulkan SDKs < 1.2.176
	version_string.Append( va( "Vulkan API %i.%i.%i", VK_VERSION_MAJOR( gpu.props.apiVersion ), VK_VERSION_MINOR( gpu.props.apiVersion ), VK_VERSION_PATCH( gpu.props.apiVersion ) ) );
#endif
```

What do you think?  Do you want me to create a pull request for this?

**Comment by r-a-sattarov** [comment]
> I think this may be the easiest way to solve it (directly in the code):
> 
> ```
> #if VK_HEADER_VERSION >= 176
> 	version_string.Append( va( "Vulkan API %i.%i.%i", VK_API_VERSION_MAJOR( gpu.props.apiVersion ), VK_API_VERSION_MINOR( gpu.props.apiVersion ), VK_API_VERSION_PATCH( gpu.props.apiVersion ) ) );
> #else
> 	// SRS - Allow deprecated version macros on older Vulkan SDKs < 1.2.176
> 	version_string.Append( va( "Vulkan API %i.%i.%i", VK_VERSION_MAJOR( gpu.props.apiVersion ), VK_VERSION_MINOR( gpu.props.apiVersion ), VK_VERSION_PATCH( gpu.props.apiVersion ) ) );
> #endif
> ```
> 
> What do you think? Do you want me to create a pull request for this? Or I can add it to one I already have pending.

I think it's a good idea. What do you think Robert @RobertBeckebans?

**Comment by RobertBeckebans** [comment]
Well the Vulkan backend never reached feature parity with OpenGL. We are currently rewriting the entire render backend using NVRHI which is a abstraction layer for DX12 and Vulkan with the ease of use of OpenGL.
It's already better than the old Vulkan backend and I guess I'm going to remove the old code next year or even sooner.

Both OpenGL and Vulkan were hindering the development for quite some time and NVRHI makes graphics programming enjoyable again. NVRHI also works on Linux and Steven Pridham already experimented with it to get it working on macOS.

**Comment by SRSaunders** [comment]
Hi Robert.  I noticed your recent bug tracking reports re NVRHI and suspected you were going this way.  As you would expect, my main concern is regarding macOS compatibility since the layer currently only works with DX11/12 and Vulkan 1.2 on Windows and Linux.  Will Steven contribute to the NVRHI project to extend its support to Mac?  I am curious whether he is experimenting directly with Metal as a back end, or whether he is looking at MoltenVK which is currently at Vulkan 1.1 only.  I am not sure what Vulkan 1.2 APIs the NVRHI layer uses, and whether that can be worked around for macOS MoltenVK.

**Comment by r-a-sattarov** [comment]
What would be the solution to this compilation error?
Check version of Vulkan libraries => 1.2.176 with cmake or add workaround in code?

**Comment by SRSaunders** [comment]
I can push this small code change as part of a pending pull request.  It's a pretty minor change and perhaps it can help you and others in the short term.  However, I won't be putting any more effort into the Vulkan backend (macOS or otherwise) given what Robert says above.

**Comment by RobertBeckebans** [comment]
Steven P already worked on the macOS version but I don't know how far he went. I think it's very unlikely that Nvidia adds a Metal backend. MoltenVK is the only chance there.

**Comment by mrcmunir** [comment]
I recommend adding Vulkan-headers as a submodule when the minimum version is not found or as optional
Pointing to https://github.com/KhronosGroup/Vulkan-Headers
This is how I got the app functional  make install on an old ubuntu 16.04/18.04 without much trouble :)

**Comment by SRSaunders** [comment]
@mrcmunir I solved it directly in the code by supporting older Vulkan SDKs which are compatible with RBDOOM-3-BFG in any case.  This approach of using compiler directives for API version compatibility is already used by RBDOOM-3-BFG in other areas of the code, e.g. ffmpeg library APIs.  If I understand it correctly, you propose adding modern Vulkan headers to a build that links to an older SDK. This method could cause breakage in other areas and I would be cautious about that - seems dangerous to me.

**Comment by r-a-sattarov** [comment]
After commit https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/56a10e713638af6f1bb94f6fbf3ddfd4818e7379 everything compiles without errors.

**Comment by yhyu13** [comment]
Updating Vulkan SDK to newer versoin would solve it. https://vulkan.lunarg.com/doc/view/latest/linux/getting_started_ubuntu.html
