### ISSUE TITLE
does not compile on ubuntu 14.10

### ISSUE THREAD

**Issue by rudl** [RobertBeckebans/RBDOOM-3-BFG#170]
compile error Lubuntu14.10 (beta):

/doom3bfg/RBDOOM-3-BFG-master/neo/renderer/Cinematic.cpp: In member function ‘bool idCinematicLocal::InitFromFFMPEGFile(const char*, bool)’:
/doom3bfg/RBDOOM-3-BFG-master/neo/renderer/Cinematic.cpp:554:60: error: ‘AVStream’ has no member named ‘r_frame_rate’
  frameRate = av_q2d( fmt_ctx->streams[video_stream_index]->r_frame_rate );
                                                            ^
CMakeFiles/RBDoom3BFG.dir/build.make:1595: recipe for target 'CMakeFiles/RBDoom3BFG.dir/renderer/Cinematic.cpp.o' failed
make[2]: *** [CMakeFiles/RBDoom3BFG.dir/renderer/Cinematic.cpp.o] Error 1
CMakeFiles/Makefile2:61: recipe for target 'CMakeFiles/RBDoom3BFG.dir/all' failed
make[1]: *** [CMakeFiles/RBDoom3BFG.dir/all] Error 2
Makefile:72: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by 9crk** [comment]
thanks a lot!  @dlemper it works!
