### ISSUE TITLE
Error when compiling Vulkan build on Ubuntu 18.04 LTS (XCB)

### ISSUE THREAD

**Issue by 10010101001** [RobertBeckebans/RBDOOM-3-BFG#437]
Error:
`/home/russell/RBDOOM-3-BFG/neo/renderer/Vulkan/RenderBackend_VK.cpp: In function ‘void CreateSurface()’:
/home/russell/RBDOOM-3-BFG/neo/renderer/Vulkan/RenderBackend_VK.cpp:423:2: error: ‘VkXcbSurfaceCreateInfoKHR’ was not declared in this scope
  VkXcbSurfaceCreateInfoKHR createInfo = {};`
I have installed xcb, libxcb1, libxcb1-dev, libx11-xcb and libx11-xcb-dev to no avail.

**Comment by spannerman79** [comment]
Did you install the vulkan sdk for your distro?

**Comment by 10010101001** [comment]
yes

**Comment by 10010101001** [comment]
I managed to fix it using a hacky way (forcing Xcb on vulkan.h) but now I get `error: ‘info’ was not declared in this scope`. Is this better or worse?
